### PR TITLE
Georgia

### PR DESCRIPTION
**Pull request by sb8244**
Howdy,

I just confirmed with a working EBT and invalid EBT locally. I used my own Twilio account (non-public) with an ngrok tunnel, so I can not provide a link for you to test with.

Steve
Code for Atlanta

### CODE REVIEW

**Comment by sb8244** [comment]
I can provide mp3 links if anyone needs that for merge.

**Comment by lippytak** [comment]
Awesome, thanks so much!

So after working on this a bit more we found a few more cases we need to test against before adding a new state. The main issue is that some states keep multiple types of benefits on the same card, which creates more possible IVR responses to deal with for valid cards. For example, if Georgia has two types of benefits on the card (say food stamps and cash) then there may be 3 different IVR responses:
1. Card with only food stamp benefits: `"your food stamp balance is $10"`
2. Card with only cash benefits: `"your cash balance is $5"`
3. Card with food stamp + cash benefits: `"your food stamp balance is $10 and your cash balance is $5"`

If so we won't be able to distinguish between 1 and 2 without looking for more keywords in the transcription (which may get unreliable).

So concretely we'll need to (1) research all possible benefit combinations for Georgia's EBT cards (2) test against all possible IVR responses with different combinations of benefits...or at least prove it's the same response regardless of the benefit combo.

Totally understandable if you aren't able to do this part and sorry we haven't updated the contrib instructions with all this yet! Feel free to ping with questions.

**Comment by sb8244** [comment]
@lippytak I do not see any reference to cash balance on SNAP https://www.ebt.acs-inc.com/gaebtclient/pdf/GA_Client_Brochure_EN.pdf;jsessionid=F92D402A2C23909597C2C9FF8717B582

I did not hear anything on the phone tree either, so I'm not sure if that would apply.

**Comment by lippytak** [comment]
Nice, looking promising. Let's do one more sanity check by calling the Georgia EBT/social services office and asking a human if the EBT card includes any benefits besides food stamps.

Maybe 1-877-423-4746 (from https://compass.ga.gov/selfservice/) will work?

If this looks good then I'll do my best to test/merge this during our next sprint.

**Comment by sb8244** [comment]
https://dfcs.dhs.georgia.gov/temporary-assistance-needy-families

It goes on ebt cards. I have no idea how to test it. One approach is to monitor transcriptions for 2 $ signs and address it then.

**Comment by sb8244** [comment]
http://www.mejp.org/content/using-your-ebt-card-get-food-supplements-or-tanf#money

More info

**Comment by sb8244** [comment]
@lippytak Is there any disadvantage to releasing one of the cards, and adding the other type of card after the fact? We haven't been able to get ahold of someone that uses the tanf program. 

One thought that I had is that you can catch the error states, and listen to the recording to figure out how to handle them going forward.

**Comment by lippytak** [comment]
Definitely possible. Will discuss with the team on Monday and figure out the best approach.

**Comment by sb8244** [comment]
Not sure what happened here. I'll close and let y'all decide

**Pull request closed without merging**
