### PR TITLE
Merge CodeForMiami's work for Florida integration

### PR DESCRIPTION
**Pull request by ErnieAtLYD**
Lead developer from Code for Miami to iterate on the branch to add Florida was Yamileth Medina (@yamilethmedina). Per her instructions:

> We need to get added to the CfA Heroku test account; we have an EBT account to work with, and while automated testing is working I can't be sure until we test with real data on the staging environment. IMO I was thinking my pull request gets accepted here, and then Code for Miami can make the pull request to Code for America. :)

### CODE REVIEW

**Comment by yamilethmedina** [comment]
Do you know why this was closed?

On Tue, May 24, 2016 at 2:47 PM, Ernie Hsiung <notifications@github.com>
wrote:

> Closed #354 <https://github.com/codeforamerica/balance/pull/354>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/balance/pull/354#event-670748171>
>



-- 
*Yami Medina*
*Web Developer: JavaScript, Ruby on Rails, HTML, CSS, and more!*
https://www.github.com/yamilethmedina
https://www.linkedin.com/in/yamilethmedina

**Comment by ErnieAtLYD** [comment]
@yamilethmedina: it's because the pull request needed to first fetch the newest commits from Code for America and get merged into your code base before you send a PR - thats why it has a lot of commits from CFA staff.

I can help you work through this if you'd like; there'd probably be a lot of conflicts where you would know best which code bases we would need to use. 

Does that make sense?

**Comment by yamilethmedina** [comment]
Oh yeah; i've experienced something similar at work with commits from
various branches. I'd really appreciate any help you could offer, though
i'll pull first and work through any merge conflicts the best I can.

On Thu, May 26, 2016 at 3:55 PM, Ernie Hsiung <notifications@github.com>
wrote:

> @yamilethmedina <https://github.com/yamilethmedina>: it's because the
> pull request needed to first fetch the newest commits from Code for America
> and get merged into your code base before you send a PR - thats why it has
> a lot of commits from CFA staff.
>
> I can help you work through this if you'd like; there'd probably be a lot
> of conflicts where you would know best which code bases we would need to
> use.
>
> Does that make sense?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/balance/pull/354#issuecomment-221976897>
>



-- 
*Yami Medina*
*Web Developer: JavaScript, Ruby on Rails, HTML, CSS, and more!*
https://www.github.com/yamilethmedina
https://www.linkedin.com/in/yamilethmedina

**Comment by daguar** [comment]
Hi! @yamilethmedina — You may be able to do this by (1) pulling down master, (2) checking out your branch, and (3) rebasing against master `git rebase master`. I am not sure how you did the commits previously, but that's the approach I take for feature branches.

**Pull request closed without merging**
