### PR TITLE
Add tests and workaround for transcriptions with individual digits #351

### PR DESCRIPTION
**Pull request by etrepum**

### CODE REVIEW

**Comment by etrepum** [comment]
This should handle #351, at least for the given samples.

**Comment by daguar** [comment]
Thank you @etrepum! I'm going to review this and get this merged — I've also gotten Twilio to hold off on the change for a few more days so I can hopefully get some more test data.

**Comment by daguar** [comment]
Finally got this merged — thanks so much again @etrepum! (The change on Twilio's end went live yesterday, so it shot right up on my list of priorities.)

**Comment by etrepum** [comment]
:+1: happy to help

**Pull request merged**
